### ISSUE TITLE
Cluster passwords cannot have ';'

### ISSUE THREAD

**Issue by aggFTW** [jupyter-incubator/sparkmagic#169]
Even though it's a valid character in basic auth, password cannot have ';'.

Line `d = dict(item.split("=") for item in connection_string.split(";"))` in `utils\utils.py` throws with:
>dictionary update sequence element #3 has length 1; 2 is required

**Comment by msftristew** [comment]
Can we not get rid of connection strings entirely? Seems like instead of using one big parameter, the "connection string", for SQL queries, we can just use three separate arguments (URL, username, password)

**Comment by aggFTW** [comment]
Yes, we could go that way.

**Comment by msftristew** [comment]
Hi all, 

I've been working on this issue.  My proposed revamp is this:

* Remove "connection strings" entirely from the codebase

* Replace each instance of a "connection string" in the codebase with a new type of object, called `Endpoint`

* Change API's for `%%spark` magic to use three separate arguments to capture an endpoint: one for URL, one for username, one for password

Since it could be more cumbersome to use 3 arguments instead of one argument argument, I believe that the best way to make this tractable would be to add "named endpoints" to the library as a feature, in the same way that named endpoints are now a feature.  So, after this work is done, you might create a Livy session like this:

    # Create an endpoint called `endp`
    %spark add -e endp --url https://example.com/livy --user admin --password 
    # Create a session called `session` at the endpoint `endp`
    %spark add -s session -l python -e endp

This proposed API uses named arguments rather than positional arguments, which the current `%%spark` API favors.  (This proposal uses the same command `add` for adding endpoints and sessions, but there could be different commands like `add-session` and `add-endpoint`, for example.)

This could also integrate with the session/endpoint management widgets so that you could (for example) use the Endpoint creation widget to create an endpoint called `e` and then run `%spark add -s s -l python -e e` to easily add a session at that endpoint.

**Comment by aggFTW** [comment]
LGTM
