### ISSUE TITLE
how to add jar dynamically?

### ISSUE THREAD

**Issue by cycorey** [jupyter-incubator/sparkmagic#260]
from [http://jupyter-incubator.github.io/declarativewidgets/docs.html](http://jupyter-incubator.github.io/declarativewidgets/docs.html)
we can see for scala 
`%addjar http://localhost:8888/nbextensions/declarativewidgets/declarativewidgets.jar`
`import declarativewidgets._`
`initWidgets`

how to support it in sparkmagic?
thanks!

**Comment by aggFTW** [comment]
Install in in the cluster. I would guess installation would look something like:
```
%%local
! pip install jupyter_declarativewidgets
```

Then, you can use `%%local` and whatever syntax declarativewidgets follow, just like any other library.

For example, from the Spark or Pyspark notebook alike (this is because the `local` context is always in Python), the way you would do this would be to use the Python bindings, like so:
```
%%local
import declarativewidgets as declwidgets
declwidgets.init()
```

**Comment by msftristew** [comment]
The question seems to be about adding Jars, not Python packages, @aggFTW  :)

**Comment by aggFTW** [comment]
I took the question as wanting to use declarativewidgets, and the add jar magic was just a way of accomplishing that.

**Comment by cycorey** [comment]
thanks, @aggFTW, but I want to ask how to add Jars, is there a magic like:
%addjar hdfs://xxx.jar
%addjar maven://[http://maven_server_address]/groupId/artifectId/version  [add all dependencies]
%addjar http://xxx.jar

**Comment by edmondja** [comment]
@aggFTW Your solution with 
"%%local
! pip install pandas
import pandas"
works fine on sparkmagic, unfortunately when I use pandas outside de jupyter cell where the library is installed, it says "NameError: name 'pandas' is not defined" can you tell me why is that ?
