### ISSUE TITLE
Added new Endpoint, Executed SQL code, Not using existing created Session

### ISSUE THREAD

**Issue by prabhu1984** [jupyter-incubator/sparkmagic#281]
Hi Experts,

I had added an endpoint and created a session. It's created an spark application and returned "application_1475230083909_12246" details. If I execute spark code using "%%spark" magic, it's executing the code using the above created session.

However, if I use "%%sql" magic and try to execute some sql code, it's creating a new session with (default endpoint provided on config.json) and then executing the sql code. Please find the behavior snapshot below and let me know your comments how to fix it.

![SparkMagic Error](https://github.com/prabhu1984/sparkmagic/blob/master/examples/images/SparkMagic%20Error.png?raw=true)

Requirement: I need to add a different endpoint, create a session and execute some spark sql.

Please guide.

Thanks!

**Comment by aggFTW** [comment]
The magics we specify there are to be used with the IPython kernel (not Spark or Pyspark kernel), as the documentation specifies.

When using the IPython kernel, the `sql` magic is not available. In order to execute SparkSQL commands, please refer to the example we pointed to previously: https://github.com/jupyter-incubator/sparkmagic/blob/master/examples/Magics%20in%20IPython%20Kernel.ipynb

where it specifies that after a session has been created, you should pass in the name of the context to use, like this:
```
%%spark -c sql
SHOW TABLES
```

**Comment by prabhu1984** [comment]
What a quickest response! Thank you so much!

**Comment by prabhu1984** [comment]
On a separate note, does jupyter-incubator/sparkmagic support Kerberized Livy? Kindly let me know.

**Comment by aggFTW** [comment]
It doesn't, but it would be a great community contribution!

**Comment by prabhu1984** [comment]
Sure, we already started working on adding kerberos support to sparkmagic, since all our livy/hadoop clusters are kerberized. Once feature completed, we would contribute to community back. Thanks for your support!

**Comment by aggFTW** [comment]
Do you want to start discussing your approach and create an issue? :)

**Comment by prabhu1984** [comment]
Sure. I created an issue `https://github.com/jupyter-incubator/sparkmagic/issues/282` to add kerberos support to sparkmagic.

My team is working on analysis and design. Will share our approach and start discussion quickly. Thanks!
