### ISSUE TITLE
Alternate method to communicate variables between livy and local (not just using %%sql -o)

### ISSUE THREAD

**Issue by nathan-gs** [jupyter-incubator/sparkmagic#327]
It would be great if we also could communicate in some way the contents of a dataframe/pandas in code, not just using the `%sql -o` way.

**Comment by aggFTW** [comment]
Hmmm, agreed that it would be great. There's some challenges to it:

1. How do you denote that you want the content to local? What syntax? In our solution, we don't want to end up using python/scala/R syntax parsers.
2. How do you specify the sample method and parameters to get the contents with? Most times, you don't want to bring the entire contents into the local context... you may run out of memory.

I'm assuming you want to do this for visualization purposes? I think that in the fullness of time, we could explore adding an additional `display` function to Livy so that it knows how to output the contents of an rdd/dataframe with a different mimetype that JupyterLab could then render itself.

What were your thoughts?

**Comment by nathan-gs** [comment]
Not that easy indeed. 

In this case the data started in Spark, was converted to Pandas, some steps using SciKit and then rendering.

If we could for example specify the variables to copy, with `%spark -o var` that would be extremely useful and flexible.

**Comment by nathan-gs** [comment]
Ps. Willing to help in getting this to work. Although my Scala is much more up to date than any Python...

**Comment by msftristew** [comment]
If you can assume the data you want to copy is a dataframe, it would be pretty easy to implement a command like `%spark -o df` that generates code to convert the dataframe `toJSON`, then do a `collect` and print everything so that you can deserialize it on the Livy end.  That just saves the step of registering the temp table and running `%sql -o` -- a bit more convenient, but not profoundly so.

Serializing and deserializing any arbitrary (non-dataframe) object would be much more difficult.

**Comment by nathan-gs** [comment]
Actually sounds like a good idea. DataFrame + scaler types would be enough.

**Comment by aggFTW** [comment]
@nathan-gs would you like to try your hand at this?

The approach would be to execute a [command](https://github.com/jupyter-incubator/sparkmagic/blob/master/sparkmagic/sparkmagic/livyclientlib/command.py) that returns the JSON representation of dataframes, to then be parsed into a pandas dataframe and put into the user's local context.

1. This is how we are getting JSON representations of dataframes for every language by creating a command and executing it: https://github.com/jupyter-incubator/sparkmagic/blob/master/sparkmagic/sparkmagic/livyclientlib/sqlquery.py#L95
1. This is how we parse the JSON text into a pandas dataframe: https://github.com/jupyter-incubator/sparkmagic/blob/master/sparkmagic/sparkmagic/livyclientlib/sqlquery.py#L74
1. This is how we define the sql magic to know what sampling options to use and whether to save it in the user's local context or not: https://github.com/jupyter-incubator/sparkmagic/blob/master/sparkmagic/sparkmagic/kernels/kernelmagics.py#L219
1. This is how we put the pandas DF into the user's context: https://github.com/jupyter-incubator/sparkmagic/blob/master/sparkmagic/sparkmagic/magics/sparkmagicsbase.py#L42

I can help with any doubts if needed :)

**Comment by orestis-ms** [comment]
@nathan-gs, I plan to take a shot at implementing what @msftristew suggested.

**Comment by lambmeh** [comment]
Just to add on to this thread, sorry if this is the wrong place to ask. Regarding communications between %%local and %%spark, is there any ways to accept input parameters in %%spark from %%local?

**Comment by aggFTW** [comment]
@lambmeh: replied here https://github.com/jupyter-incubator/sparkmagic/issues/332

**Comment by orestis-ms** [comment]
@nathan-gs @aggFTW I've made a pull request for this feature. In the pull request I'm also detailing a few possible directions (1 for code, 1 for functionality)
