### ISSUE TITLE
[Bug] Miss-matching Types in a SQL HiveContext saving in a python panda

### ISSUE THREAD

**Issue by roblax** [jupyter-incubator/sparkmagic#330]
Hi,

We are taken Data from Hive a CDH 5.9 Cluster to local with Livy and Sparkmagic.

Sparkmagic is inference that a Double Hive to like datetime64[ns]

![sparkmagic_error_types](https://cloud.githubusercontent.com/assets/7288474/22934722/4e0d55c6-f2d0-11e6-87dc-df6eefb5da7c.jpg)
 
The information is unreadble with this format 

![sparkmagic_error_data](https://cloud.githubusercontent.com/assets/7288474/22934742/6201122a-f2d0-11e6-8ecd-837d132b1585.jpg)

¿Someone could take me a solution?

**Comment by aggFTW** [comment]
We didn't intend to have matching types. We are applying coercion into what pandas thinks is best: https://github.com/jupyter-incubator/sparkmagic/blob/master/sparkmagic/sparkmagic/utils/utils.py#L44

One way to fix this would be to add a parameter to skip the coercion, getting strings back all the time. User would be responsible of applying type coercion as needed.

For now, you could always coerce into whatever type. In your example, you would do something like:

```
%%local
import pandas as pd
misfeaturesPd['cd1'] = pd.to_numeric(misfeaturesPd['cd1'], errors="raise")
```

**Comment by roblax** [comment]
Thanks for the explanation, 

I understand that you will not try to keep the same data types as in the hive table but I think that the coercion of a Double value with many decimals couldn't be coerced to Datetime64[ns] .

Thanks, sparkmagic is being a great solution for us.

**Comment by aggFTW** [comment]
Huh... I was not aware that this would happen. I think that, for now, you can comment this out in your installation in order to mitigate: https://github.com/jupyter-incubator/sparkmagic/blob/0bfa932c90344417fd441c67a28cab053f45a32e/sparkmagic/sparkmagic/livyclientlib/sqlquery.py#L90
and then do the coercing manually to the types you need.

Let us think about how best to solve this for now. We might simply make the coercion optional.
