### ISSUE TITLE
SQL Magic %%sql drops column if first row value is null/NaN

### ISSUE THREAD

**Issue by danfike** [jupyter-incubator/sparkmagic#346]
It seems that the dataframe visualization for an SQL query will exclude a column outright if the first row contains a `NULL` or `NaN` value for that column.

Consider this example, where the only difference between the queries is the `ORDER` of the results.
![image](https://cloud.githubusercontent.com/assets/8999918/25245572/7d32f8a6-25ca-11e7-8862-351f3d74480d.png)

## Observed with
notebook 4.4.1
sparkmagic 0.11.1
kernel PySpark

## Courtesy Text for Copy/Paste:
```
%%sql
select * from (
  select 1 as foo, 2 as bar
  union all
  select 3, NULL
) x
order by bar asc
```

**Comment by aggFTW** [comment]
Thanks for reporting!

This is a bug in how we are specifying the columns: https://github.com/jupyter-incubator/sparkmagic/blob/master/sparkmagic/sparkmagic/utils/utils.py#L72

The reason we specify the columns at all is to preserve the order of the columns (via the ordered dict). We take the columns by looking at the keys from the first row, but the first row could have less columns if anything was `NULL`. So, this will not drop columns (because the first row has both foo and bar):

`[OrderedDict([(u'foo', 1), (u'bar', 2)]), OrderedDict([(u'foo', 3)])]`

but this will:

`[OrderedDict([(u'foo', 3)]), OrderedDict([(u'foo', 1), (u'bar', 2)])]`

A fix could be to not specify the columns, so pandas won't drop anything, and then assign the columns later. If we try to assign less columns than the dataframe has, we'll get a `ValueError`.

So, line 72 would be replaced by this:

```
df = pd.DataFrame(data_array)
for data in data_array:
    try:
        df.columns = data.keys()
        break
    except ValueError as e:
        print(e)
        pass
```

I would like to add some unit tests for this case before I submit a PR, but I don't think I'll be able to get to that this week. If you are comfortable with it, feel free to submit a PR that I can review. If not, I'll get to it soon and you can just patch your existing installation with the code above.

**Comment by edoardovivo** [comment]
Hello... any news on this? 
Just stumbled upon this issue and it's quite scary...
Thanks a lot!

**Comment by aggFTW** [comment]
Fixed it. Only edge case not covered is one where you get something like:

```
%%sql
select * from (
  select 1 as foo
  union all
  select 2 as bar
  union all
  select 3 as foobar
) x
order by bar asc
```

We will not drop any columns (foo, bar, foobar will be in there), but we cannot guarantee any order of columns.
