### ISSUE TITLE
%%sql reads float columns as datetime 64 in the pandas DataFrame

### ISSUE THREAD

**Issue by vidit-bhatia** [jupyter-incubator/sparkmagic#366]
I uploaded data in my pyspark notebook most of the data in my columns is of type float I cast it explicitly to float using this command
`btcUSD = btcUSD.withColumn("Open", btcUSD["Open"].cast("float")).\
        withColumn("High", btcUSD["High"].cast("float")).\
        withColumn("Close", btcUSD["Close"].cast("float")).\
        withColumn("Low", btcUSD["Low"].cast("float")).\
        withColumn("Volume_(BTC)", btcUSD["Volume_(BTC)"].cast("float")).\
        withColumn("Volume_(Currency)", btcUSD["Volume_(Currency)"].cast("float")).\
        withColumn("Weighted_Price", btcUSD["Weighted_Price"].cast("float")).\
        withColumn("Timestamp", btcUSD["Timestamp"].cast('long'))`

Next I sample the data in dataframe using
`btcUSDSample=btcUSD.sample(False,0.1,23)
sqlContext.registerDataFrameAsTable(btcUSDSample,'testTable')`

After this I run the following

`%%sql -o tables
Select low from testTable`

Now If I run the following
`%%local
tables.dtypes`

It gives me 
`low    datetime64[ns]
dtype: object`'

I do not understand why is this always read as dattime . Even when I try to do select * from testTable everything is read as datetime.

![image](https://user-images.githubusercontent.com/3845645/27158223-cf937cb2-511a-11e7-81f9-3bfdfae9db13.png)

**Comment by aggFTW** [comment]
That iss because of this line of code:
https://github.com/jupyter-incubator/sparkmagic/blob/5bd377d7e79b418723b05978dae70c17b1c18761/sparkmagic/sparkmagic/utils/utils.py#L47

This has given us headaches before... not sure if the right fix is to make coercing optional or what to do exactly. If we don't coerce, lots of graphs don't work by default since it's always dealing with strings. Coercing to numeric first and date later makes so that some date types are always shown as numerics (the opposite of your problem). I would suggest, as a workaround, that you manually comment out the code to do the coercing, as explained here: https://github.com/jupyter-incubator/sparkmagic/issues/330

I will start working on making coercing optional.

**Comment by vidit-bhatia** [comment]
Can we request Livy to give us the schema of the remote dataframe and use that decide whether to convert to date or number rather than use Json to first create the pandas dataframe and if it is object decide whether to convert it to date or number.

WDYT?

I am new to sparkmagic and scala but if u provide me some help i can take a stab to solve this in the above discussed way

**Comment by aggFTW** [comment]
Yes, we could probably do that. If you want to take a stab at it, I would suggest doing the following:

1. Figure out what code you need in Pyspark/Spark/SparkR to get the schema for any dataframe and what possible values you can get. Consider all edge cases/what to do when schema cannot be gotten, etcetera.
2. Figure out the mapping between possible pyspark/spark/sparkr data types and numpy datatypes to properly coerce them.
3. Create a coercing function that takes the dataframe and the schema.
4. Write a function that sends the code just like SQLQuery does to get the schema after the dataframe has been received. Look at https://github.com/jupyter-incubator/sparkmagic/blob/master/sparkmagic/sparkmagic/livyclientlib/sqlquery.py#L71
5. Write unit tests for all of this.

Does that make sense?
