### ISSUE TITLE
Enable SSL support for Livy Endpoints

### ISSUE THREAD

**Issue by a-romero** [jupyter-incubator/sparkmagic#377]
When trying to add an SSL'd Livy server Endpoint the following error is thrown:

`TypeError: unorderable types: NoneType() >= int()`

Works well with non-SSL'd Livy Endpoints.

**Comment by aggFTW** [comment]
SSL endpoints working fine in our deployments and from my box, so maybe there's some misconfiguration. What is the full stack trace? Can you share your config.json for the SSL endpoints you are using? Please change with dummy username/passwords/parts of urls, but I want to see the overall structure of the file.

**Comment by a-romero** [comment]
Hi,

Stack trace, config and log attached. 

The logs indicate the handshake has failed. We use CA-signed certificates from our internal CA authority. Do your deployments use self-signed certificates? The browser already has the Root CA certificates imported so would have thought it should already work.


[config.json.txt](https://github.com/jupyter-incubator/sparkmagic/files/1111702/config.json.txt)
[log_290617.log.txt](https://github.com/jupyter-incubator/sparkmagic/files/1111695/log_290617.log.txt)
[stack_trace.log.txt](https://github.com/jupyter-incubator/sparkmagic/files/1111697/stack_trace.log.txt)

**Comment by aggFTW** [comment]
What version of sparkmagic do you have? Can you please update to the latest (0.12.1 atm, I believe)? I see from the stacktrace that you don't have the latest code, which checks if status_code is None.

That said, I believe the problem is coming from your certs, as you mentioned. Your browser having the authority is not a fix because sparkmagic is a server-side component. You can either enable `"ignore_ssl_errors": true,` in your `config.json` to accept your certs or you can follow any of these threads:

https://stackoverflow.com/questions/39356413/how-to-add-a-custom-ca-root-certificate-to-the-ca-store-used-by-python-in-window/39358282

or better yet, you could submit a patch to sparkmagic to be able to configure the verify parameter in the requests library: https://stackoverflow.com/questions/30405867/how-to-get-python-requests-to-trust-a-self-signed-ssl-certificate

Please let me know if you got your issue fixed.

**Comment by aggFTW** [comment]
Closing for now due to no response.
