### ISSUE TITLE
Setting up a practical use case starting from this repository

### ISSUE THREAD

**Issue by jmeidam** [jupyter-incubator/sparkmagic#385]
I am very excited that I finally managed to get a Jupyter notebook, using external Spark resources, to run from a Docker container thanks to the work done in this repository. However, now I am struggling to translate this into a practical use case.

I am currently running into a few snags (I have only basic experience using Spark or Docker), and would like to seek help on this list. I would like to handle this step-by-step and not expose all the issues I am facing straight away, to keep this thread clear. (I am not claiming any of these issues have to do with the code base, they are simply due to my lack of expertise.)

My eventual goal is to have a containerized application (either running a Jupyter notebook, or even better, standalone python scripts) that can be deployed on any Spark cluster (e.g. on Azure or Amazon). Furthermore, for testing the way this repository is set up seems ideal. I do not want to setup Azure resources during a testing and debugging phase.

My starting point is a fresh clone of this repository, on which I ran the docker commands to build and run the Spark and Jupyter containers, i.e.
```
git clone https://github.com/jupyter-incubator/sparkmagic.git
docker-compose build
docker-compose up
```
I am now able to run a Jupyter notebook on localhost:8888, and the pyspark3 kernel does its job (I prefer to use Python3).

### Issue 1

Currently, the numpy package is not recognised. Adding the line `RUN pip install numpy` to the file `Dockerfile.jupyter` and rebuilding, does not install the numpy package in the same environment as used by the pyspark3 kernel. 

How can I install package X in my jupyter container?

An interesting observation from running the Jupyter pyspark3 kernel is that I am accessing different environments when using `%%bash` or the os library:
```
%%bash
ls /home
--------
jovyan
```

```
os.listdir("/home")
--------
[]
```

### Issue 2

This is very much related to issue 1. My reason for wanting a Jupyter notebook to run in a container without the need to include an entire Spark installation is to keep the container small and allow for the possibility to run it locally as easily as having it use a remote cluster. It would also be very convenient for workshops and/or demos. 

How can I set up my own Jupyter docker container, containing all the python packages I need so that it can be easily deployed anywhere, using any Spark resources?

**Comment by aggFTW** [comment]
Happy to know this is useful to you.

>My eventual goal is to have a containerized application (either running a Jupyter notebook, or even better, standalone python scripts) that can be deployed on any Spark cluster (e.g. on Azure or Amazon). Furthermore, for testing the way this repository is set up seems ideal. I do not want to setup Azure resources during a testing and debugging phase.

It seems like you want to develop an app, test, and then deploy to multiple cloud instances. Let's break it down:

1. Developing can be done in this docker containers just to get a feel for APIs and try the logic of the program. Please note that because you are running in a container, you cannot process big data on it, so this is only to get a feel for the APIs that Spark offers and how it works.
1. Testing the app requires that you test the errors conditions that happen on your full dataset. Maybe you need to tune your Spark application due to OOM errors or etcetera. This means that you need to be able to deploy your code in an Azure/AWS/on-prem cluster and test your real workload.
1. Deploying can then be done in a variety of ways once you know the app is correct and you have tuned Spark to your liking. This can be done via spark-submit (ssh) or via an endpoint like Livy (http).

> How can I install package X?
I'll complete the reply later today or tomorrow as to how to figure out how to install things. But I'm guessing you can install via 

```
%%bash
pip install <package>
```

and then restart the kernel.
I cannot try right now if it works or not.

As for issue 2, you would create an image just like we created ours to install sparkmagic on it.

**Comment by jmeidam** [comment]
```
%%bash
pip install numpy
```

Is does not do the trick, it says numpy is already installed:
```
Requirement already satisfied (use --upgrade to upgrade): numpy in /opt/conda/lib/python3.5/site-packages
```

I think this has to do with `%%bash ls /` giving different results from `os.listdir('/')`. Numpy is already installed in whatever environment bash is seeing, but it is not installed in whatever the Python session is seeing. Is there perhaps an environment variable I need to set from either inside the Jupyter notebook, or from Dockerfile.jupyter?

Concerning your point 3. I had difficulties getting a docker container with my Spark-using-python-code to execute using an Azure Spark cluster. There one has to use the Livy endpoint it seems, with which I could not seem to submit a `docker run` command. Using `spark-submit` was a bust as well because I could not find the URL for the master node. But I am getting ahead of things. I would first like to try and get the Jupyter notebook to run using Numpy.

**Comment by aggFTW** [comment]
It seems like you are accessing two environments (the bash magic is seeing your host OS and the python sessions is seeing your Jupyter image... i find this weird but cannot check now since I'm traveling), and you may need to install numpy via the docker image itself. 

As to how to submit things to an Azure cluster, please see https://docs.microsoft.com/en-us/azure/hdinsight/hdinsight-apache-spark-livy-rest-interface
There's no way to submit a docker run command to the cluster. spark-submit would work by ssh'ing to the headnode of the cluster: https://docs.microsoft.com/en-us/azure/hdinsight/hdinsight-hadoop-linux-use-ssh-unix

Adding your own notebooks to the docker image is not something we support as of now, as it's meant to be a try-it experience and not a workflow replacement. Please refer to docker documentation or forums for building your own image or how to mount volumes. We may reconsider this in the future.

**Comment by jmeidam** [comment]
I do seem to be accessing two environments, but it is not my host machine that is accessed.
With `docker-compose up` I'm running two images: sparkmagic-jupyter and sparkmagic-livy.
With the bash magic I seem to be able to access whatever is on sparkmagic-jupyter (I checked this with `docker run sparkmagic-jupyter ls /home`). With the os package from the notebook I seem to be accessing the other image (again, I verified this).

I would like to avoid installing Numpy and any more specific dependencies in the Livy container as that stuff should go in the Jupyter container. The Jupyter container is supposed to be the standalone containerized version of the app that has the ability to connect to any external Spark cluster (momentarily this cluster is simulated with the sparkmagic-livy container, which is great for now).

If I really can only use spark-submit, then that means I need to install spark in my sparkmagic-jupyter container as well right? Does the spark-submit command require the entire Spark installation?

> Please refer to docker documentation or forums for building your own image or how to mount volumes. We may reconsider this in the future.

I do understand how to create my own image and how to mount volumes, the problem is that the volumes I mount cannot be seen by the notebook due to the issue in the first paragraph. If we can find a way to fix that, I think I will be very close to achieving my goals.

And have a great trip :)

**Comment by aggFTW** [comment]
Argh, that makes total sense, and I'm sorry I didn't think of that earlier. Yes, you will be accessing Livy's python environment, in the Livy container. My apologies.

>I would like to avoid installing Numpy and any more specific dependencies in the Livy container as that stuff should go in the Jupyter container.

That is unfortunately not possible since Livy is the one that is in the cluster, and will be executing the code. Livy needs to have all the libraries installed. 

>If I really can only use spark-submit, then that means I need to install spark in my sparkmagic-jupyter container as well right? Does the spark-submit command require the entire Spark installation?

You can use Livy to submit Spark applications, as I've shared above. You can also use spark-submit via ssh into the cluster, where spark-submit is already installed; instructions are also above for Azure clusters. You wouldn't use spark-submit from your container.

>due to the issue in the first paragraph

I'm assuming you are referring to how to start the Jupyter server from a certain location so that the notebooks are picked up once you have already mounted your notebooks to the Jupyter container? You can set the location to start from by using the `NotebookApp.notebook_dir` setting as referenced in https://jupyter-notebook.readthedocs.io/en/latest/config.html

>And have a great trip :)

Thanks!

**Comment by jmeidam** [comment]
> That is unfortunately not possible since Livy is the one that is in the cluster, and will be executing the code. Livy needs to have all the libraries installed.

That is indeed unfortunate. Doesn't that negate the whole purpose of wanting to have an app in a Docker container? I thought it was very convenient to have my notebook, any modules it relies on and perhaps some additional scripts all contained in a single distributable container. Now it seems I still need to upload all those things to a Spark cluster to be able to run spark-submit, or even use Livy. 

So what I think I should do now in order to have my notebook run my spark code, is install all dependencies, including the notebook containing the actual code into the sparkmagic-livy image (not the small sparkmagic-jupyter one). 
If I am getting this right, in practice this would mean having to install all that stuff on the headnode of whichever Spark cluster I wish to use. This also means that in practice I might as well forget about Docker.

**Comment by aggFTW** [comment]
For your app to be in a Docker container the cluster would also have to be containerized. This means that yes, in practice you need to have everything in the headnode. HDInsight Spark clusters already come with everything most people need already installed in the cluster (Jupyter, Livy, Anaconda, and etcetera).

**Comment by aggFTW** [comment]
Should I close this issue now?

**Comment by jmeidam** [comment]
Yes, I think that's ok. Too bad there's no solution. I have learned a few things while messing around with all this. Thanks for the help and swift replies!
