### ISSUE TITLE
Outstanding sessions unusable after notebook restart

### ISSUE THREAD

**Issue by pranayhasan** [jupyter-incubator/sparkmagic#387]
If some reason the notebook server is shutdown, upon restart the sessions that are outstanding (running on Livy side) aren't reusable. These sessions keep showing up only in manage endpoints but not in manage sessions leading to inconsistent behavior for users. 

<img width="895" alt="screen shot 2017-07-24 at 4 52 00 pm" src="https://user-images.githubusercontent.com/5507845/28521275-7aeaca2c-7090-11e7-8457-16f69b59ece8.png">

<img width="904" alt="screen shot 2017-07-24 at 4 51 46 pm" src="https://user-images.githubusercontent.com/5507845/28521278-7f94f552-7090-11e7-9599-f715520f6c82.png">

These go away when user explicitly cleans up the endpoint.

### Fix for the consistent behavior

1. Make outstanding sessions not usable by making changes to not display sessions that doesn't exist in the manage sessions UI.
2. Automatically create a new LivySession for all the outstanding sessions. The names for these sessions need to be automated (Maybe a random 5 character word).

The later way is more involved and challenging.

@aggFTW please take a look and let me know your thoughts on this issue.

**Comment by aggFTW** [comment]
Thanks to the session heartbeat feature on Livy, this should not be the case and the sessions should go away after the hearbeat expires. Do you have it turned on?

**Comment by pranayhasan** [comment]
Yes, but in the case when the session heartbeat is off by setting it to 0, we need a way to invalidate the sessions. 
It is because of the session heartbeat is posing problems where when users leave the laptop idle and if it goes to sleep, the sessions go away on Livy side. But as the widget UI is not refreshed, the users assume that the session exists.

One way is to refresh the widget UI periodically to be on synch with Livy state. Or the other way is to bring the session back if the session heartbeat is off. I believe there should be a refresh button on widget UI irrespective of what we do.

**Comment by aggFTW** [comment]
Sorry, but I'm having trouble understanding the way your users are using this functionality.

The principle we followed when creating this functionality was that someone needs to have the responsibility for the lifetime of the session. Sessions needs to be cleaned up when they are no longer used so as not to leak cluster resources.

When heartbeats are on, the kernel has the responsibility of cleaning up the session when the kernel is stopped. Of course, if the machine where the kernel lives sleeps, the heartbeat won't be sent. The way to get around this currently is to turn heartbeats off.

When heartbeats are off, the responsibility on cleaning up sessions is on the user who created them in the first place. This user will use a combination of `Manage Sessions` and `Manage Endpoints` to achieve the clean up. `Manage Sessions` should display sessions that the current kernel is using, and not all sessions from the endpoint; you can only delete sessions that you created from this kernel here. `Manage Endpoints` is used to manage the endpoint and all of its sessions, including sessions created elsewhere.

When you say:

>Make outstanding sessions not usable by making changes to not display sessions that doesn't exist in the manage sessions UI.

Outstanding sessions are already not usable by the kernel, since they have no name to reference them. However, the user may want to delete/clean up the endpoint from the kernel if they  notice an outstanding session.

Can you please explain what not showing them in the `Manage Endpoints` tab accomplishes?

**Comment by pranayhasan** [comment]
@aggFTW From the perspective of our users, the notebook should replace spark-shell. So, most of them couldn't understand why the sessions that exist on **Manage Endpoints** aren't visible in **Manage Sessions**. From users point of view, **Manage Endpoints** is to identify the sessions created to their corresponding endpoints.

So, basically as you mentioned, in the current way the **Manage Sessions** widget UI is coupled with the kernel. We want a way in which the users see the same UI in any of the notebooks that is opened to give a consistent experience.

**Comment by aggFTW** [comment]
It can follow the spark-shell model if you use the individual-language kernels, which launch only the one spark context and does not require users to manage their sessions. If users are taking the ipython kernel with the magics to manage endpoints, they need to be educated about how the system works, and they need to be aware about the need to clean up their resources if heartbeat was turned off.

If you want to keep heartbeat on to relieve your users from this burden, you could provision notebook servers for your users in a VM with JupyterHub or some similar alternative.

I don't see how best to empower users to clean up but to leave a `Manage Sessions` panel, and a `Manage Endpoints` panel for easy delete.

I HIGHLY discourage this and think that your users need education:
If your users are getting confused by `Manage Endpoints`, you could submit  a pull request to turn off the displaying of sessions in the `Manage Endpoint` tab via a config flag that is turned on by default.

**Comment by aggFTW** [comment]
@pranayhasan: should we close this issue?

**Comment by pranayhasan** [comment]
@aggFTW Yes, I'm closing this. Thanks!
