### ISSUE TITLE
Using "GRANT_SUDO=yes" doesn't work for the docker-compose

### ISSUE THREAD

**Issue by DShevelev** [jupyter-incubator/sparkmagic#416]
I get sudo non-funcional in the up-to-date master built and up with the docker-compose even though I do specify GRANT_SUDO=yes in my docker-compose.yml:
version: "3"
services:
  spark:
    image: jupyter/sparkmagic-livy
    build:
      context: .
      dockerfile: Dockerfile.spark
    hostname: spark
    ports:
      - "8998:8998"
  jupyter:
    image: jupyter/sparkmagic
    build:
      context: .
      dockerfile: Dockerfile.jupyter
      args:
        dev_mode: "false"
    links:
      - spark
    ports:
      - "8888:8888"
    environment:
      **- GRANT_SUDO=yes**
![image](https://user-images.githubusercontent.com/32962992/32491320-f0f238b4-c3be-11e7-9601-e1f5d4993ffd.png)
Is enabling running sudo under jovyan user without a password supposed to work in the sparkmagic project?
The issue looks to appear in the Jupyter project time and again:
In the https://github.com/jupyter/docker-stacks/issues/408 "just installed the docker image-requesting sudo password for jovyan" it was reported to be present and then disappeared after yet another download of the project.
In the https://github.com/jupyter/docker-stacks/issues/394 "Using "GRANT_SUDO=yes" doesn't work" the GRANT_SUDO did not work because of corrupted /etc/sudoers
Is it possible something is just not upgraded in the sparkmagic project to make it work?

**Comment by aggFTW** [comment]
The docker images provided here are provided as a showcase of how things work, how to set it up, and the architecture, and they are not provided as a means to do serious work, given that livy/spark are running in a single container. That said, you can modify the docker container and the docker-compose file as appropriate.

Maybe @apetresc would have some idea on how to make it work since he knows way more about docker than I do 😄. I would reach out to the Jupyter community as well, asking them how to set up one of their docker images in a docker-compose environment with this requirement of being able to run sudo from a notebook.

**Comment by ZmeiGorynych** [comment]
After trying many permutations, this worked for me:
```
    environment:
      GRANT_SUDO: "yes"
    user: root
```
In particular the `user:root` part was necessary

**Comment by rjurney** [comment]
What is the point of sudo if the user is root? I don't get this. I read this in the documentation and it makes little sense.
