### ISSUE TITLE
Issue creating endpoint with sparkmagic in jupyter lab

### ISSUE THREAD

**Issue by kherrmann2** [jupyter-incubator/sparkmagic#499]
Hey all,

I've been working with a developer to help them setup their jupyter container to run sparkmagic, connecting to a remote livy server.  I had been running my tests against just Jupyter notebook, but when I went to port my setup into the developers jupyter notebook I discovered that he is running a jupyter lab.  

Unfortunately, whenever I attempt to add an endpoint, I get absolutely no output.  When I run the jupyterlab in debug mode, the only message I get is "Error" whenever I click to add an endpoint.  The kernel shows some activity in the UI, but no error is generated there...just blank.  

Is there an issue running sparkmagic in jupyter labs?  Any ideas how I could get more details from the debug log other than "error"?  

Thank you!

**Comment by kherrmann2** [comment]
Does the %manage_spark dialog window use the prompt-toolkit?  If so, perhaps it's a dependency issue, as I see there is a version mismatch for prompt-toolkit.  

The strange thing there is that it works with a jupyter notebook, but not lab.

**Comment by metrofun** [comment]
@kherrmann2 I'm having the same issue. It works in Notebook, but not JupyterHub. Have you solved it?

**Comment by kherrmann2** [comment]
Unfortunately, I wasn't able to locate the fix for this issue...and they ended up going a different path independently of that issue.

**Comment by lrodgers36** [comment]
Any update on this?

**Comment by itamarst** [comment]
I will try to take a look later in the week.

**Comment by itamarst** [comment]
This is a documentation issue: in order to use the widget library, you need to run:

```
jupyter labextension install @jupyter-widgets/jupyterlab-manager
```

(See https://ipywidgets.readthedocs.io/en/stable/user_install.html#installing-the-jupyterlab-extension)

I've updated the README installation documentation to address this. Thanks for the bug report, and let us know if this doesn't solve your problem.

**Comment by ikiw** [comment]
@itamarst : even i face the same issue with the latest sparkmagic. The issue is the %manage_spark widget loads. But on add endpoint, the success/error message doesn't get displayed. The internal functionality works but the output messages aren't getting displayed. Can you please suggest some pointers ?
