### ISSUE TITLE
Print progress while session is being created

### ISSUE THREAD

**Issue by aggFTW** [jupyter-incubator/sparkmagic#51]
Give the user some kind of feedback so that user knows that code is not frozen.

**Comment by msftristew** [comment]
Here's a module for rich progress bars: https://pypi.python.org/pypi/ipy-progressbar/1.0.2

Since Livy doesn't give us rich info surrounding session creation progress, this is probably overkill.  A few short sentences that say something along the lines of "Contacting Livy to start session... Waiting for Livy session to return to idle state..." is probably fine.
