### ISSUE TITLE
[BUG] When executing a SparkMagic kernel through Papermill, the Livy session is not removed on exiting

### ISSUE THREAD

**Issue by withsmilo** [jupyter-incubator/sparkmagic#649]
**Describe the bug**
I'm testing that running the SparkMagic kernel through `Papermill` works fine. But I found a bug that if the SparkMagic kernel is executed via `Papermill`, the Livy session does not close when the job is finished. I don't think this is intended.

**Expected behavior**
The Livy session should be closed.

**Versions:**
 - SparkMagic : 0.15.0
 - Livy (if you know it) : 0.7.0-incubating
 - Spark : 2.4

**Comment by devstein** [comment]
@withsmilo This is a known issue/feature. Please refer to the [papermill section in the README](https://github.com/jupyter-incubator/sparkmagic#papermill)

**Comment by withsmilo** [comment]
@devstein 
Thanks for the guide. If this is a known issue, why not fix it? I'm trying to fix this issue now.

**Comment by devstein** [comment]
@withsmilo The issue is that there is a fundamental difference in functionality for the typical "interactive notebook" use case and the "functional notebook" papermill use case. 

In the interactive experience, the user wants to encounter a Spark error, see the error, fix the bug, and re-run it using the same spark session.  

In the functional (papermill) experience, the users want the spark error logged, the session to be shut down, and the process to exit with a failure code

**Comment by withsmilo** [comment]
@devstein I agree. However, even if the (SparkMagic + Papermill) completes normally without any error, the related Livy session does not shut down. `cleanup_all_sessions_on_exit` is not the answer, because we are running multiple Livy sessions on the one endpoint at the same time.

**Comment by devstein** [comment]
@withsmilo  Great point, I actually have been meaning to address this. We've been using a fork I created that fixes this issue: [see this commit](https://github.com/viaduct-ai/sparkmagic/commit/81f40c7291723c26da2e6210225d3f772dcf1064)

I'll see if I have time in the next few days to contribute back to the main repository! Otherwise, feel free to use our fork.

**Comment by withsmilo** [comment]
@devstein Thanks for sharing. But, your commit is related to the error case. I am trying to handle it in the [SessionManager](https://github.com/jupyter-incubator/sparkmagic/blob/0.15.0/sparkmagic/sparkmagic/livyclientlib/sessionmanager.py#L79-L91) after adding a new configuration for Papermill.

**Comment by withsmilo** [comment]
@devstein 
I found that this issue was raised from Papermill, not SparkMagic. We should use Papermill<2.0.0 instead of the latest version to avoid this issue.

**Comment by devstein** [comment]
@withsmilo Okay, thanks for looking into this! Out of curiosity, what is the issue with `papermill 2.0.0`?

**Comment by gthomas-slack** [comment]
@withsmilo I'm looking to do something very similar with `sparkmagic` + `papermill` with spak sessiions running on a multi-use Spark/Livy cluster.

What setup did you end up going with? vanilla `papermill`< 2.0.0, or @devstein's fork?

Thanks!

**Comment by withsmilo** [comment]
@devstein @gthomas-slack 
After downgrading `Papermill` to 1.2.1, the Livy session created by `SparkMagic` ends normally. However, there still seems to be a problem that makes Livy unstable.

**Comment by gthomas-slack** [comment]
Oh what is that instability @withsmilo ? So far with my testing of @devstein's fork + `papermill` 1.2.1 everything seems to run well, and sessions are closed. I've not yet investigated what is going wrong with `2.0.0`+

**Comment by withsmilo** [comment]
@gthomas-slack 
I am looking for what makes Livy unstable. The cause may or may not be `SparkMagic`.

**Comment by devstein** [comment]
@withsmilo Ok, let us know if it's related to `sparkmagic`. We run [`papermill==2.1.1`](https://github.com/viaduct-ai/papermill) (forked with the pyspark/spark kernels) without any issues
