### ISSUE TITLE
Publish sparkmagic Docker images regularly

### ISSUE THREAD

**Issue by iirekm** [jupyter-incubator/sparkmagic#789]
At hub.docker.com there seem to be no official images.

There is a Dockerfile in repo, but I can't build it (because of https://github.com/jupyter-incubator/sparkmagic/issues/776 ). Having prebuilt images would make life easier, and would avoid incompatibilities with libraries as the bug above.

**Comment by devstein** [comment]
@iirekm Users of Sparkmagic typically have to customize the Docker images to meet their infrastructure requirements. I believe we should have a set of official images, but I don't think publishing the current Dockerfile would be very useful to users (let me know if you think otherwise).

For avoiding incompatibilities like #776, I completely agree. An simple approach is to run the unit and integration tests nightly. I've made an issue for tracking https://github.com/jupyter-incubator/sparkmagic/issues/791
